name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Run tests
        run: yarn test
      # Testing the SBOM API /repos/{owner}/{repo}/dependency-graph/sbom  
      - name: Test GitHub url
        run: echo "GitHub SBOM API URL - ${{ github.api_url }}/repos/${{ github.repository_owner }}/${{ github.repository }}/dependency-graph/sbom"
